/*
 * Copyright (c) 2023-2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

/*
 * Board definitions of the RMCS Slave Lite (HPM5361, QFN48).
 * Derived from the HPM SDK v1.13.0 board hpm5300evk: the generic board services are kept,
 * the definitions of the evk hardware are removed, and the RMCS Slave Lite peripherals are
 * added. Pins are set by init_bsp_pins() and clocks by init_clocks(), both generated by
 * the HPM Pinmux Tool from tool_config.hpmpc.
 */

#ifndef _HPM_BOARD_H
#define _HPM_BOARD_H
#include <stdio.h>
#include <stdarg.h>
#include "hpm_common.h"
#include "hpm_clock_drv.h"
#include "hpm_soc.h"
#include "hpm_soc_feature.h"
#include "pinmux.h"
#if !defined(CONFIG_NDEBUG_CONSOLE) || !CONFIG_NDEBUG_CONSOLE
#include "hpm_debug_console.h"
#endif

#define BOARD_NAME          "RMCS_Slave_Lite"
#define BOARD_UF2_SIGNATURE (0x0A4D5048UL)
#define BOARD_DFU_SIGNATURE (0x48504D21UL)

#ifndef BOARD_RUNNING_CORE
#define BOARD_RUNNING_CORE HPM_CORE0
#endif

/* console section: UART0 on PY00 (TX) / PY01 (RX), pins are set by init_bsp_pins() */
#if !defined(CONFIG_NDEBUG_CONSOLE) || !CONFIG_NDEBUG_CONSOLE
#ifndef BOARD_CONSOLE_TYPE
#define BOARD_CONSOLE_TYPE CONSOLE_TYPE_UART
#endif

#if BOARD_CONSOLE_TYPE == CONSOLE_TYPE_UART
#ifndef BOARD_CONSOLE_UART_BASE
#define BOARD_CONSOLE_UART_BASE       HPM_UART0
#define BOARD_CONSOLE_UART_CLK_NAME   clock_uart0
#define BOARD_CONSOLE_UART_IRQ        IRQn_UART0
#define BOARD_CONSOLE_UART_TX_DMA_REQ HPM_DMA_SRC_UART0_TX
#define BOARD_CONSOLE_UART_RX_DMA_REQ HPM_DMA_SRC_UART0_RX
#endif
#define BOARD_CONSOLE_UART_BAUDRATE (115200UL)
#endif
#endif

/* Peripherals used by User/app_main.cpp; the pins are routed by init_bsp_pins() and
 * init_bsp_jtag_shared_pins(). */

/* BMI088 chip selects and interrupt lines */
#define BOARD_IMU_CS_GYRO_GPIO_CTRL  HPM_GPIO0
#define BOARD_IMU_CS_GYRO_GPIO_INDEX GPIO_DI_GPIOB
#define BOARD_IMU_CS_GYRO_GPIO_PIN   11
#define BOARD_IMU_CS_ACCEL_GPIO_CTRL  HPM_GPIO0
#define BOARD_IMU_CS_ACCEL_GPIO_INDEX GPIO_DI_GPIOB
#define BOARD_IMU_CS_ACCEL_GPIO_PIN   13
#define BOARD_IMU_INT_GYRO_GPIO_CTRL  HPM_GPIO0
#define BOARD_IMU_INT_GYRO_GPIO_INDEX GPIO_DI_GPIOB
#define BOARD_IMU_INT_GYRO_GPIO_PIN   12
#define BOARD_IMU_INT_ACCEL_GPIO_CTRL  HPM_GPIO0
#define BOARD_IMU_INT_ACCEL_GPIO_INDEX GPIO_DI_GPIOB
#define BOARD_IMU_INT_ACCEL_GPIO_PIN   10

/* User key on PA07 (JTAG-shared), pull-up, low when pressed */
#define BOARD_KEY_GPIO_CTRL        HPM_GPIO0
#define BOARD_KEY_GPIO_INDEX       GPIO_DI_GPIOA
#define BOARD_KEY_GPIO_PIN         7

/* USB0 on PA24/PA25; PA31 reads the HS/FS switch */
#define BOARD_USB_SW_GPIO_CTRL  HPM_GPIO0
#define BOARD_USB_SW_GPIO_INDEX GPIO_DI_GPIOA
#define BOARD_USB_SW_GPIO_PIN   31

#ifndef BOARD_SHOW_CLOCK
#define BOARD_SHOW_CLOCK 1
#endif
#ifndef BOARD_SHOW_BANNER
#define BOARD_SHOW_BANNER 1
#endif

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

void board_init(void);
void board_init_console(void);
void board_init_clock(void);
void board_init_clock_group(void);
void board_init_usb_dp_dm_pins(void);
void board_init_pmp(void);
void board_print_banner(void);
void board_print_clock_freq(void);
void board_delay_us(uint32_t us);
void board_delay_ms(uint32_t ms);
void board_ungate_mchtmr_at_lp_mode(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus */
#endif /* _HPM_BOARD_H */
