
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 */

#include "clock.h"
#include "hpm_soc.h"
#include "hpm_clock_drv.h"
#include "hpm_pllctlv2_drv.h"


void init_clocks(void)
{
    /* Generate pll0 code */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, 40, 0);

    /* Generate clk0_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk0, pllctlv2_div_1p0);

    /* Generate clk1_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk1, pllctlv2_div_1p6);

    /* Generate clk2_pll0 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL0, pllctlv2_clk2, pllctlv2_div_2p4);

    /* Generate pll1 code */
    pllctlv2_set_pll_with_mfi_mfn(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, 40, 0);

    /* Generate clk0_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk0, pllctlv2_div_1p2);

    /* Generate clk1_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk1, pllctlv2_div_1p6);

    /* Generate clk2_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk2, pllctlv2_div_2p4);

    /* Generate clk3_pll1 code */
    pllctlv2_set_postdiv(HPM_PLLCTLV2, PLLCTLV2_PLL_PLL1, pllctlv2_clk3, pllctlv2_div_3p0);

    /* Generate clk_top_can0 code */
    clock_set_source_divider(clock_can0, clk_src_pll1_clk0, 10);

    /* Generate clk_top_can1 code */
    clock_set_source_divider(clock_can1, clk_src_pll1_clk0, 10);

    /* Generate clk_top_can2 code */
    clock_set_source_divider(clock_can2, clk_src_pll1_clk0, 10);

    /* Generate clk_top_can3 code */
    clock_set_source_divider(clock_can3, clk_src_pll1_clk0, 10);

    /* Generate clk_top_urt0 code */
    clock_set_source_divider(clock_uart0, clk_src_pll1_clk0, 10);

    /* Generate clk_top_urt2 code */
    clock_set_source_divider(clock_uart2, clk_src_pll1_clk0, 10);

    /* Generate clk_top_urt7 code */
    clock_set_source_divider(clock_uart7, clk_src_pll1_clk0, 10);

    /* Generate clk_top_spi1 code */
    clock_set_source_divider(clock_spi1, clk_src_pll1_clk0, 10);

    /* Generate clk_top_tmr0 code */
    clock_set_source_divider(clock_gptmr0, clk_src_pll1_clk0, 8);

    /* Generate clk_top_tmr2 code */
    clock_set_source_divider(clock_gptmr2, clk_src_pll1_clk0, 8);

    /* Generate clk_usb0 code */
    clock_set_source_divider(clock_cpu0, clk_src_pll0_clk0, 2);

    clock_add_to_group(clock_can0, 0);

    clock_add_to_group(clock_can1, 0);

    clock_add_to_group(clock_can2, 0);

    clock_add_to_group(clock_can3, 0);

    clock_add_to_group(clock_gptmr0, 0);

    clock_add_to_group(clock_gptmr2, 0);

    clock_add_to_group(clock_spi1, 0);

    clock_add_to_group(clock_uart0, 0);

    clock_add_to_group(clock_uart2, 0);

    clock_add_to_group(clock_uart7, 0);

    clock_add_to_group(clock_usb0, 0);
}
